# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nDep-5kY47amUcxir6eUV9akYSa3x34T
"""

import pandas as pd
import numpy as np

df = pd.DataFrame(pd.read_csv('/content/train.csv'))
df.head()

df.shape[0]

df.isnull().sum()

x = df.isnull().sum()
drop_col = x[x>(35/100 * df.shape[0])]
drop_col

df.shape[0] * 35/100

drop_col.index

df.drop(drop_col.index, axis=1, inplace = True)
df.isnull().sum()

df.corr()

df['Embarked'].describe()

df['Embarked'].fillna('S', inplace=True)

df.isnull().sum()

df.corr()

df['FamilySize'] = df['SibSp']+df['Parch']
df.drop(['SibSp', 'Parch'] , axis = 1, inplace = True)
df.corr()

df['Alone'] = [0 if df['FamilySize'][i]>0 else 1 for i in df.index]
df.head()

df.groupby(['Alone'])['Survived'].mean()

df[['Alone']].corr( )

df[['Alone','Fare']].corr()

df['Sex'] = [0 if df['Sex'][i]=='male' else 1 for i in df.index]
df.groupby(['Sex'])['Survived'].mean()

df.groupby(['Embarked'])['Survived'].mean()